### ISSUE TITLE
Bad Format On Movie.md (template)

### ISSUE THREAD

**Issue by mi6i** [Gubchik123/obsidian-movie-search-plugin#2]
Hello man actually I pasted your template into movie.md file, but the format is bad which part of it should be changed, or can you send your template correctly ? (I'm new to obsidian)

![image](https://github.com/Gubchik123/obsidian-movie-search-plugin/assets/87862455/bcc5c894-34cd-4b7d-8762-922ed446d7d8)

![image](https://github.com/Gubchik123/obsidian-movie-search-plugin/assets/87862455/dce6b705-e4c9-4138-80e8-5b0ded90e923)

**Comment by Gubchik123** [comment]
Hello, on your screenshot I see that you don't close note properties, that's why it's highlighted with red color. Add "---" after banner link. 

Also fix place with `media_type` variable and update it to the following one: `{{media_type}}` (without useless spaces).

**Comment by mi6i** [comment]
Thanks.

**Comment by Gubchik123** [comment]
You're welcome! If you have any more questions or need further assistance, feel free to reach out anytime. Happy to help! 😊🎬
